/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/health': {
		/** Health */
		get: operations['health_health_get']
	}
}

export type webhooks = Record<string, never>

export type components = Record<string, never>

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
	/** Health */
	health_health_get: {
		responses: {
			/** @description Successful Response */
			200: {
				content: {
					'application/json': {
						[key: string]: string
					}
				}
			}
		}
	}
}
